# Generated by Django 3.1.4 on 2020-12-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapuser',
            name='last_sync',
            field=models.DateTimeField(blank=True, default=None, help_text='Last time performed LDAP sync for user attributes and group membership', null=True),
        ),
    ]
